# Site settings
title: Tushita Sarkar's CV 
description: ddbullfrog's CV
favicon: /assets/img/avatar.JPG
baseurl: https://ddbullfrog.github.io/resumecard
url: https://ddbullfrog.github.io/resumecard
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Tushita Sarkar
  title: Data Analyst
  address: Breda, Netherlands
  email: sarkarsecret@gmail.com
  link: https://eagleeyevision.nl/
  weibo:
  linkedin: ddbullfrog
  twitter: ddbullfrog
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: XXX Ltd
      location: Auckland, New Zealand
      title: Java Developer
      started: 2014
      duration: (2014 - Present)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work2:
      company: XXX Ltd
      location: Shanghai, China
      title: Java Developer
      started: 2012
      duration: (2012 - 2014)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work3:
      company: XXX Ltd
      location: Shanghai, China
      title: Java Developer
      started: 2009
      duration: (2009 - 2012)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  educationHistory:
    - education1:
      organization: XXXXXX University
      location: Shenyang, China
      degree: Bachelor
      major: Software Engineering
      started: 2005
      duration: (2005 - 2009)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  languages:
    - language1:
      name: English
      proficiency: Professional
    - language2:
      name: Dutch
      proficiency: Professional
    - language3:
      name: Hindi
      proficiency: Native
    - language3:
      name: Bengali
      proficiency: Native
